# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            anovMari
tagline:          'Nerd&#39;s Thoughts'
description:      'Programmatic & Pragmatic'
cname:            anovmari.com
baseurl:          /
posts_img:    "/public/img/for"

author:
  name:           'Anton Marianov'
  url:            https://twitter.com/anovmari

paginate:         5

gems:
  - jekyll-sitemap
  - jekyll-mentions

jekyll-mentions:
  base_url: https://github.com

github:
  repo:           https://github.com/anovmari
