# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            anovMari
tagline:          'Nerd&#39;s Thoughts'
description:      'It is everything that makes me happy. Read it. Like it. Share it.'
cname:            anovmari.com
baseurl:          /

author:
  name:           'Anton Marianov'
  url:            https://twitter.com/anovmari

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/anovmari
