# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            anovMari
tagline:          'Nerd&#39;s Thoughts'
description:      'It is everything that makes me happy. Read it. Like it. Share it.'
cname:            anovmari.com
baseurl:          /
post_img_path:    /public/img/a

author:
  name:           'Anton Marianov'
  url:            https://twitter.com/anovmari

paginate:         5

gems:
  - jekyll-sitemap

github:
  repo:           https://github.com/anovmari
